version: "3.9"
services:
  env:
    build: 
      dockerfile: ./Dockerfile
    hostname: avr-env
    container_name: avr-env
    volumes:
      - type: bind
        target: /root
        source: ./avr-root
    tty: true
    stdin_open: true

