version: "3.9"
services:
  my_service:
    image: avr-env
    hostname: avr-env
    container_name: avr-container
    volumes:
      - type: bind
        target: /root
        source: ./avr-root

    command: ["sleep", "86400"]

